<?php

return [
    [
        'type_id' => '1',
        "title" => "SpotifyWeb",
        "author" => "Lamberto Neri",
        "creation_date" => "2023-03-22",
        "last_update" => "2023-03-27",
        "collaborators" => "",
        "description" => "clone of spotify",
        "image"       => "uploads/SpotifyWeb.jpeg",
        "technologies" => [1],
        "link_github" => "https://github.com/LambertoNeri/html-css-spotifyweb.git",
    ],
    [
        'type_id' => '1',
        "title" => "Minefield",
        "author" => "Lamberto Neri",
        "creation_date" => "2023-04-26",
        "last_update" => "2023-04-26",
        "collaborators" => "",
        "description" => "clone of minefield",
        "image"       => "uploads/Campominato.jpeg",
        "technologies" => [1, 2],
        "link_github" => "https://github.com/LambertoNeri/js-campominato-dom.git",
    ],
    [
        'type_id' => '1',
        "title" => "Social Posts",
        "author" => "Lamberto Neri",
        "creation_date" => "2023-05-03",
        "last_update" => "2023-05-03",
        "collaborators" => "",
        "description" => "clone of social",
        "image"       => "uploads/SocialPosts.jpeg",
        "technologies" => [1, 2],
        "link_github" => "https://github.com/LambertoNeri/js-social-posts.git",
    ],
    [
        'type_id' => '1',
        "title" => "Boolzapp",
        "author" => "Lamberto Neri",
        "creation_date" => "2023-05-10",
        "last_update" => "2023-05-16",
        "collaborators" => "",
        "description" => "clone of whatsapp",
        "image"       => "uploads/Boolzapp.jpeg",
        "technologies" => [1, 3],
        "link_github" => "https://github.com/LambertoNeri/vue-boolzapp.git",
    ],
    [
        'type_id' => '1',
        "title" => "Boolflix",
        "author" => "Lamberto Neri",
        "creation_date" => "2023-05-24",
        "last_update" => "2023-05-26",
        "collaborators" => "",
        "description" => "clone of netflix",
        "image"       => "uploads/Boolflix.jpeg",
        "technologies" => [1, 3],
        "link_github" => "https://github.com/LambertoNeri/vite-boolflix.git",
    ],
    [
        'type_id' => '1',
        "title" => "Football League",
        "author" => "Lamberto Neri",
        "creation_date" => "2023-05-29",
        "last_update" => "2023-06-06",
        "collaborators" => "",
        "description" => "clone of football league page",
        "image"       => "uploads/FootballLeague.jpeg",
        "technologies" => [1, 3],
        "link_github" => "https://github.com/LambertoNeri/proj-html-vuejs.git",
    ],
    [
        'type_id' => '2',
        "title" => "Travel Agency",
        "author" => "Lamberto Neri",
        "creation_date" => "2023-07-04",
        "last_update" => "2023-07-04",
        "collaborators" => "Felice D'Arcangelo - Lamberto Neri - Nicola Soggiu - Giulio D'Angelo - Domenico Ferrari",
        "description" => "clone of travel agency",
        "image"       => "uploads/LaravelBoolean.jpeg",
        "technologies" => [5],
        "link_github" => "https://github.com/LambertoNeri/laravel-boolean.git",
    ],
    
];